apiVersion: apps/v1
# apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-db
  labels:
    app: mydb
spec:
  selector:
    matchLabels:
      app: mydb
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
      - image: mongo
        name: mydatabase
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        ports:
        - containerPort: 27017


